---
layout: cv
title: Ross Pence Resume
---
# Ross Pence
Computer Science and Software Engineering Major

<div id="webaddress">
208-671-3736
| <a href="mailto:rosspence14@gmail.com">rosspence14@gmail.com</a>
| <a href="#">LinkedIn Profile (Optional)</a>
| <a href="#">E-Portfolio (Optional)</a>
</div>


## Education

`April 2025 - Present`
__Brigham Young University - Idaho__, Rexburg, ID

- Computer Science and Software Engineering Major
- 4.00 GPA at BYUI
- Won third place at a BYU-I Hackathon as a team of two by writing a computer game in Unity using C#
- Built Python projects using Tkinter, Math, Pygame, and Turtle
- Created 3D models of car parts, drone parts, human and animal characters, desk organizers, laptop stands, and other objects using Blender and OnShape (CAD)
- 3D printed designed objects using an Ender 3 v2 Pro printer
- Served as lead developer with 2 junior developers

`April 2025 - Present`
__Brigham Young University - Idaho__, Rexburg, ID

- AI/ML Minor
- Engineered an end-to-end machine learning pipeline using Polars and Python, implementing and evaluating four predictive models to achieve 90% accuracy
- Engineered a machine learning pipeline using Polars and Scikit-learn, implementing Random Forest and XGBoost ensembles to compare performance metrics and improve prediction accuracy


## Projects

- Competed as a programmer and driver of multiple teams' robots at the 2022 VEX World Championship
- Configured BetaFlight for drone motor control, transmitter/receiver communication, and FPV video systems (digital and analog)
- Tuned PID controller gains, battery charge levels, joystick sensitivities, and flight mode selection via radio control transmitter


## Experience

`January 2026 - April 2026`
__PlaybookOps - Software Engineering Intern__, Rexburg, Idaho

- Full-Stack Developer
- Architected and deployed a full-stack dynamic web application using HTML5, CSS3, and Node.js, integrating a SQL database for real-time data persistence
- Collaborated with a cross-functional team of four to deliver high-quality project assets within an accelerated 3-month timeline

`January 2026 - April 2026`
__Brigham Young University Idaho__, Rexburg, Idaho

- Teaching Assistant - Web Development
- Evaluated and provided detailed feedback on 100+ student projects, ensuring adherence to modern web standards and clean code practices
- Debugged complex student code, resolving technical blockers in HTML5, CSS3, and JavaScript

